name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer Docker
      run: |
        docker run --rm -e BUILDOZER_ALLOW_INSTALL_AS_ROOT=1 -v ${{ github.workspace }}:/workdir -w /workdir kivy/buildozer:latest sh -c "yes | buildozer android debug"
        sudo chown -R $USER:$USER .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: esp32app-apk
        path: bin/*.apk
        
